import type { City } from './cities'

/**
 * The curated city list, with coordinates from the GeoNames gazetteer.
 *
 * GENERATED by scripts/build-city-list.mjs — edit scripts/cities.source.json
 * and run that script rather than editing this file by hand.
 *
 * Place data from https://www.geonames.org, CC BY 4.0.
 */
export const CITY_LIST: City[] = [
  {
    key: 'vancouver-island:victoria',
    name: 'Victoria',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.4359,
    longitude: -123.35155,
    spanMetres: 10000
  },
  {
    key: 'vancouver-island:saanich',
    name: 'Saanich',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.54964,
    longitude: -123.36931,
    spanMetres: 7500
  },
  {
    key: 'vancouver-island:oak-bay',
    name: 'Oak Bay',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.44964,
    longitude: -123.3026,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:esquimalt',
    name: 'Esquimalt',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.43569,
    longitude: -123.41174,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:langford',
    name: 'Langford',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.44963,
    longitude: -123.50261,
    spanMetres: 7500
  },
  {
    key: 'vancouver-island:colwood',
    name: 'Colwood',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.43293,
    longitude: -123.48591,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:sooke',
    name: 'Sooke',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.37463,
    longitude: -123.72762,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:sidney',
    name: 'Sidney',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.64964,
    longitude: -123.40262,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:duncan',
    name: 'Duncan',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.78293,
    longitude: -123.70266,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:ladysmith',
    name: 'Ladysmith',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.99016,
    longitude: -123.81699,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:chemainus',
    name: 'Chemainus',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.91633,
    longitude: -123.71937,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:nanaimo',
    name: 'Nanaimo',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.16638,
    longitude: -123.94003,
    spanMetres: 7500
  },
  {
    key: 'vancouver-island:lantzville',
    name: 'Lantzville',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.2454,
    longitude: -124.07547,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:parksville',
    name: 'Parksville',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.31947,
    longitude: -124.31575,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:qualicum-beach',
    name: 'Qualicum Beach',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.34783,
    longitude: -124.44231,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:port-alberni',
    name: 'Port Alberni',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.24133,
    longitude: -124.8028,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:tofino',
    name: 'Tofino',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.15314,
    longitude: -125.90744,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:ucluelet',
    name: 'Ucluelet',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.94153,
    longitude: -125.54635,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:courtenay',
    name: 'Courtenay',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.68657,
    longitude: -124.9936,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:comox',
    name: 'Comox',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.68294,
    longitude: -124.93613,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:cumberland',
    name: 'Cumberland',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.61634,
    longitude: -125.03613,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:campbell-river',
    name: 'Campbell River',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 50.01634,
    longitude: -125.24459,
    spanMetres: 5000
  },
  {
    key: 'vancouver-island:gold-river',
    name: 'Gold River',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.78091,
    longitude: -126.05013,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:port-mcneill',
    name: 'Port McNeill',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 50.59,
    longitude: -127.08638,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:port-hardy',
    name: 'Port Hardy',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 50.72086,
    longitude: -127.49231,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:alert-bay',
    name: 'Alert Bay',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 50.58377,
    longitude: -126.92707,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:port-alice',
    name: 'Port Alice',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 50.38447,
    longitude: -127.45101,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:tahsis',
    name: 'Tahsis',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.92526,
    longitude: -126.6549,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:bamfield',
    name: 'Bamfield',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.83577,
    longitude: -125.14018,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:cowichan-bay',
    name: 'Cowichan Bay',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.73366,
    longitude: -123.61739,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:shawnigan-lake',
    name: 'Shawnigan Lake',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.65055,
    longitude: -123.64494,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:mill-bay',
    name: 'Mill Bay',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.65,
    longitude: -123.55,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:ganges',
    name: 'Ganges',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 48.85342,
    longitude: -123.50032,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:gabriola',
    name: 'Gabriola',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.17043,
    longitude: -123.8499,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:denman-island',
    name: 'Denman Island',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.53294,
    longitude: -124.8195,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:hornby-island',
    name: 'Hornby Island',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 49.53448,
    longitude: -124.66923,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:quathiaski-cove',
    name: 'Quathiaski Cove',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 50.05153,
    longitude: -125.22013,
    spanMetres: 3200
  },
  {
    key: 'vancouver-island:sointula',
    name: 'Sointula',
    country: 'Canada',
    region: 'vancouver-island',
    latitude: 50.63079,
    longitude: -127.01775,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:vancouver',
    name: 'Vancouver',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.24966,
    longitude: -123.11934,
    spanMetres: 13000
  },
  {
    key: 'british-columbia:burnaby',
    name: 'Burnaby',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.26636,
    longitude: -122.95263,
    spanMetres: 10000
  },
  {
    key: 'british-columbia:richmond',
    name: 'Richmond',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.17003,
    longitude: -123.13683,
    spanMetres: 10000
  },
  {
    key: 'british-columbia:surrey',
    name: 'Surrey',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.10635,
    longitude: -122.82509,
    spanMetres: 10000
  },
  {
    key: 'british-columbia:delta',
    name: 'Delta',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.08917,
    longitude: -123.05322,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:new-westminster',
    name: 'New Westminster',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.20678,
    longitude: -122.91092,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:coquitlam',
    name: 'Coquitlam',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.2846,
    longitude: -122.78217,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:port-coquitlam',
    name: 'Port Coquitlam',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.26637,
    longitude: -122.76932,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:port-moody',
    name: 'Port Moody',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.28124,
    longitude: -122.82457,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:north-vancouver',
    name: 'North Vancouver',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.31636,
    longitude: -123.06934,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:west-vancouver',
    name: 'West Vancouver',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.3286,
    longitude: -123.16019,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:langley',
    name: 'Langley',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.10107,
    longitude: -122.65883,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:maple-ridge',
    name: 'Maple Ridge',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.21939,
    longitude: -122.60193,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:white-rock',
    name: 'White Rock',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.02049,
    longitude: -122.79507,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:abbotsford',
    name: 'Abbotsford',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.05798,
    longitude: -122.25257,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:chilliwack',
    name: 'Chilliwack',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.16638,
    longitude: -121.95257,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:mission',
    name: 'Mission',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.13298,
    longitude: -122.30258,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:hope',
    name: 'Hope',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.38299,
    longitude: -121.44144,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:harrison-hot-springs',
    name: 'Harrison Hot Springs',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.29969,
    longitude: -121.78586,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:squamish',
    name: 'Squamish',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.69925,
    longitude: -123.15631,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:whistler',
    name: 'Whistler',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.11817,
    longitude: -122.95396,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:pemberton',
    name: 'Pemberton',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.31641,
    longitude: -122.80273,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:lions-bay',
    name: 'Lions Bay',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.45218,
    longitude: -123.2376,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:gibsons',
    name: 'Gibsons',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.39539,
    longitude: -123.50555,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:sechelt',
    name: 'Sechelt',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.47512,
    longitude: -123.75903,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:powell-river',
    name: 'Powell River',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.83278,
    longitude: -124.52368,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:kamloops',
    name: 'Kamloops',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.66648,
    longitude: -120.3192,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:kelowna',
    name: 'Kelowna',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.88307,
    longitude: -119.48568,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:west-kelowna',
    name: 'West Kelowna',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.8625,
    longitude: -119.58333,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:vernon',
    name: 'Vernon',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.26729,
    longitude: -119.27337,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:penticton',
    name: 'Penticton',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.48062,
    longitude: -119.58584,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:summerland',
    name: 'Summerland',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.59977,
    longitude: -119.66911,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:peachland',
    name: 'Peachland',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.76862,
    longitude: -119.74633,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:osoyoos',
    name: 'Osoyoos',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.03306,
    longitude: -119.45237,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:oliver',
    name: 'Oliver',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.18306,
    longitude: -119.5524,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:salmon-arm',
    name: 'Salmon Arm',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.69981,
    longitude: -119.26907,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:revelstoke',
    name: 'Revelstoke',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.99712,
    longitude: -118.1953,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:golden',
    name: 'Golden',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 51.29995,
    longitude: -116.9689,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:nelson',
    name: 'Nelson',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.49985,
    longitude: -117.28553,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:castlegar',
    name: 'Castlegar',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.32317,
    longitude: -117.65831,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:trail',
    name: 'Trail',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.09983,
    longitude: -117.70223,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:rossland',
    name: 'Rossland',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.08313,
    longitude: -117.80224,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:cranbrook',
    name: 'Cranbrook',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.49991,
    longitude: -115.76879,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:kimberley',
    name: 'Kimberley',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.67071,
    longitude: -115.9776,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:fernie',
    name: 'Fernie',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.49996,
    longitude: -115.06871,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:invermere',
    name: 'Invermere',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.51666,
    longitude: -116.03538,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:creston',
    name: 'Creston',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.09987,
    longitude: -116.50211,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:grand-forks',
    name: 'Grand Forks',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.03309,
    longitude: -118.4356,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:merritt',
    name: 'Merritt',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.11225,
    longitude: -120.7942,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:princeton',
    name: 'Princeton',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 49.45802,
    longitude: -120.51076,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:lillooet',
    name: 'Lillooet',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.6856,
    longitude: -121.942,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:ashcroft',
    name: 'Ashcroft',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.72372,
    longitude: -121.28207,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:cache-creek',
    name: 'Cache Creek',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 50.81011,
    longitude: -121.3246,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:100-mile-house',
    name: '100 Mile House',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 51.64982,
    longitude: -121.28594,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:williams-lake',
    name: 'Williams Lake',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 52.14153,
    longitude: -122.14451,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:quesnel',
    name: 'Quesnel',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 52.97842,
    longitude: -122.4931,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:prince-george',
    name: 'Prince George',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 53.9166,
    longitude: -122.75301,
    spanMetres: 7500
  },
  {
    key: 'british-columbia:vanderhoof',
    name: 'Vanderhoof',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 54.01657,
    longitude: -124.01982,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:burns-lake',
    name: 'Burns Lake',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 54.22972,
    longitude: -125.76084,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:smithers',
    name: 'Smithers',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 54.78036,
    longitude: -127.17428,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:terrace',
    name: 'Terrace',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 54.51634,
    longitude: -128.60345,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:kitimat',
    name: 'Kitimat',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 54.05244,
    longitude: -128.65342,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:prince-rupert',
    name: 'Prince Rupert',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 54.31507,
    longitude: -130.32098,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:masset',
    name: 'Masset',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 54.01141,
    longitude: -132.14707,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:daajing-giids',
    name: 'Daajing Giids',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 53.25494,
    longitude: -132.08788,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:bella-coola',
    name: 'Bella Coola',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 52.37183,
    longitude: -126.7539,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:dawson-creek',
    name: 'Dawson Creek',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 55.75984,
    longitude: -120.2403,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:fort-st-john',
    name: 'Fort St. John',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 56.24988,
    longitude: -120.85292,
    spanMetres: 5000
  },
  {
    key: 'british-columbia:chetwynd',
    name: 'Chetwynd',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 55.69988,
    longitude: -121.63627,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:tumbler-ridge',
    name: 'Tumbler Ridge',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 55.13027,
    longitude: -120.99415,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:mackenzie',
    name: 'Mackenzie',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 55.33637,
    longitude: -123.09374,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:valemount',
    name: 'Valemount',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 52.83329,
    longitude: -119.2525,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:mcbride',
    name: 'McBride',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 53.29995,
    longitude: -120.16932,
    spanMetres: 3200
  },
  {
    key: 'british-columbia:fort-nelson',
    name: 'Fort Nelson',
    country: 'Canada',
    region: 'british-columbia',
    latitude: 58.80533,
    longitude: -122.7002,
    spanMetres: 3200
  },
  {
    key: 'wales:cardiff',
    name: 'Cardiff',
    country: 'Wales',
    region: 'wales',
    latitude: 51.48,
    longitude: -3.18,
    spanMetres: 10000
  },
  {
    key: 'wales:swansea',
    name: 'Swansea',
    country: 'Wales',
    region: 'wales',
    latitude: 51.62079,
    longitude: -3.94323,
    spanMetres: 7500
  },
  {
    key: 'wales:newport',
    name: 'Newport',
    country: 'Wales',
    region: 'wales',
    latitude: 51.58774,
    longitude: -2.99835,
    spanMetres: 7500
  },
  {
    key: 'wales:wrexham',
    name: 'Wrexham',
    country: 'Wales',
    region: 'wales',
    latitude: 53.04664,
    longitude: -2.99132,
    spanMetres: 7500
  },
  {
    key: 'wales:bangor',
    name: 'Bangor',
    country: 'Wales',
    region: 'wales',
    latitude: 53.22752,
    longitude: -4.12936,
    spanMetres: 5000
  },
  {
    key: 'wales:st-davids',
    name: 'St Davids',
    country: 'Wales',
    region: 'wales',
    latitude: 51.88094,
    longitude: -5.26554,
    spanMetres: 3200
  },
  {
    key: 'wales:st-asaph',
    name: 'St Asaph',
    country: 'Wales',
    region: 'wales',
    latitude: 53.25815,
    longitude: -3.44524,
    spanMetres: 3200
  },
  {
    key: 'wales:aberystwyth',
    name: 'Aberystwyth',
    country: 'Wales',
    region: 'wales',
    latitude: 52.41548,
    longitude: -4.08292,
    spanMetres: 5000
  },
  {
    key: 'wales:llandudno',
    name: 'Llandudno',
    country: 'Wales',
    region: 'wales',
    latitude: 53.32498,
    longitude: -3.83148,
    spanMetres: 5000
  },
  {
    key: 'wales:conwy',
    name: 'Conwy',
    country: 'Wales',
    region: 'wales',
    latitude: 53.28077,
    longitude: -3.83039,
    spanMetres: 3200
  },
  {
    key: 'wales:caernarfon',
    name: 'Caernarfon',
    country: 'Wales',
    region: 'wales',
    latitude: 53.14126,
    longitude: -4.27016,
    spanMetres: 5000
  },
  {
    key: 'wales:porthmadog',
    name: 'Porthmadog',
    country: 'Wales',
    region: 'wales',
    latitude: 52.92924,
    longitude: -4.13137,
    spanMetres: 3200
  },
  {
    key: 'wales:harlech',
    name: 'Harlech',
    country: 'Wales',
    region: 'wales',
    latitude: 52.85941,
    longitude: -4.10831,
    spanMetres: 3200
  },
  {
    key: 'wales:barmouth',
    name: 'Barmouth',
    country: 'Wales',
    region: 'wales',
    latitude: 52.72377,
    longitude: -4.05748,
    spanMetres: 3200
  },
  {
    key: 'wales:dolgellau',
    name: 'Dolgellau',
    country: 'Wales',
    region: 'wales',
    latitude: 52.74222,
    longitude: -3.88611,
    spanMetres: 3200
  },
  {
    key: 'wales:machynlleth',
    name: 'Machynlleth',
    country: 'Wales',
    region: 'wales',
    latitude: 52.58965,
    longitude: -3.85308,
    spanMetres: 3200
  },
  {
    key: 'wales:aberaeron',
    name: 'Aberaeron',
    country: 'Wales',
    region: 'wales',
    latitude: 52.24247,
    longitude: -4.25871,
    spanMetres: 3200
  },
  {
    key: 'wales:cardigan',
    name: 'Cardigan',
    country: 'Wales',
    region: 'wales',
    latitude: 52.08373,
    longitude: -4.66228,
    spanMetres: 3200
  },
  {
    key: 'wales:fishguard',
    name: 'Fishguard',
    country: 'Wales',
    region: 'wales',
    latitude: 51.99376,
    longitude: -4.97631,
    spanMetres: 3200
  },
  {
    key: 'wales:haverfordwest',
    name: 'Haverfordwest',
    country: 'Wales',
    region: 'wales',
    latitude: 51.80169,
    longitude: -4.96914,
    spanMetres: 5000
  },
  {
    key: 'wales:tenby',
    name: 'Tenby',
    country: 'Wales',
    region: 'wales',
    latitude: 51.67279,
    longitude: -4.70447,
    spanMetres: 3200
  },
  {
    key: 'wales:pembroke',
    name: 'Pembroke',
    country: 'Wales',
    region: 'wales',
    latitude: 51.67464,
    longitude: -4.91286,
    spanMetres: 3200
  },
  {
    key: 'wales:milford-haven',
    name: 'Milford Haven',
    country: 'Wales',
    region: 'wales',
    latitude: 51.71278,
    longitude: -5.0341,
    spanMetres: 5000
  },
  {
    key: 'wales:narberth',
    name: 'Narberth',
    country: 'Wales',
    region: 'wales',
    latitude: 51.79784,
    longitude: -4.74275,
    spanMetres: 3200
  },
  {
    key: 'wales:saundersfoot',
    name: 'Saundersfoot',
    country: 'Wales',
    region: 'wales',
    latitude: 51.70945,
    longitude: -4.70215,
    spanMetres: 3200
  },
  {
    key: 'wales:carmarthen',
    name: 'Carmarthen',
    country: 'Wales',
    region: 'wales',
    latitude: 51.85552,
    longitude: -4.30535,
    spanMetres: 5000
  },
  {
    key: 'wales:llanelli',
    name: 'Llanelli',
    country: 'Wales',
    region: 'wales',
    latitude: 51.68195,
    longitude: -4.16191,
    spanMetres: 5000
  },
  {
    key: 'wales:ammanford',
    name: 'Ammanford',
    country: 'Wales',
    region: 'wales',
    latitude: 51.79279,
    longitude: -3.98833,
    spanMetres: 3200
  },
  {
    key: 'wales:llandovery',
    name: 'Llandovery',
    country: 'Wales',
    region: 'wales',
    latitude: 51.99415,
    longitude: -3.79637,
    spanMetres: 3200
  },
  {
    key: 'wales:lampeter',
    name: 'Lampeter',
    country: 'Wales',
    region: 'wales',
    latitude: 52.11285,
    longitude: -4.08039,
    spanMetres: 3200
  },
  {
    key: 'wales:new-quay',
    name: 'New Quay',
    country: 'Wales',
    region: 'wales',
    latitude: 52.21515,
    longitude: -4.35887,
    spanMetres: 3200
  },
  {
    key: 'wales:tregaron',
    name: 'Tregaron',
    country: 'Wales',
    region: 'wales',
    latitude: 52.2195,
    longitude: -3.93295,
    spanMetres: 3200
  },
  {
    key: 'wales:neath',
    name: 'Neath',
    country: 'Wales',
    region: 'wales',
    latitude: 51.66317,
    longitude: -3.80443,
    spanMetres: 5000
  },
  {
    key: 'wales:port-talbot',
    name: 'Port Talbot',
    country: 'Wales',
    region: 'wales',
    latitude: 51.59241,
    longitude: -3.78019,
    spanMetres: 5000
  },
  {
    key: 'wales:bridgend',
    name: 'Bridgend',
    country: 'Wales',
    region: 'wales',
    latitude: 51.50583,
    longitude: -3.57722,
    spanMetres: 5000
  },
  {
    key: 'wales:maesteg',
    name: 'Maesteg',
    country: 'Wales',
    region: 'wales',
    latitude: 51.60926,
    longitude: -3.65823,
    spanMetres: 3200
  },
  {
    key: 'wales:merthyr-tydfil',
    name: 'Merthyr Tydfil',
    country: 'Wales',
    region: 'wales',
    latitude: 51.74794,
    longitude: -3.37779,
    spanMetres: 5000
  },
  {
    key: 'wales:aberdare',
    name: 'Aberdare',
    country: 'Wales',
    region: 'wales',
    latitude: 51.71438,
    longitude: -3.44918,
    spanMetres: 5000
  },
  {
    key: 'wales:pontypridd',
    name: 'Pontypridd',
    country: 'Wales',
    region: 'wales',
    latitude: 51.6021,
    longitude: -3.34211,
    spanMetres: 5000
  },
  {
    key: 'wales:caerphilly',
    name: 'Caerphilly',
    country: 'Wales',
    region: 'wales',
    latitude: 51.57452,
    longitude: -3.218,
    spanMetres: 5000
  },
  {
    key: 'wales:ebbw-vale',
    name: 'Ebbw Vale',
    country: 'Wales',
    region: 'wales',
    latitude: 51.77714,
    longitude: -3.20792,
    spanMetres: 3200
  },
  {
    key: 'wales:tredegar',
    name: 'Tredegar',
    country: 'Wales',
    region: 'wales',
    latitude: 51.77251,
    longitude: -3.24679,
    spanMetres: 3200
  },
  {
    key: 'wales:abergavenny',
    name: 'Abergavenny',
    country: 'Wales',
    region: 'wales',
    latitude: 51.82098,
    longitude: -3.01743,
    spanMetres: 3200
  },
  {
    key: 'wales:monmouth',
    name: 'Monmouth',
    country: 'Wales',
    region: 'wales',
    latitude: 51.81265,
    longitude: -2.71363,
    spanMetres: 3200
  },
  {
    key: 'wales:chepstow',
    name: 'Chepstow',
    country: 'Wales',
    region: 'wales',
    latitude: 51.64087,
    longitude: -2.67683,
    spanMetres: 3200
  },
  {
    key: 'wales:usk',
    name: 'Usk',
    country: 'Wales',
    region: 'wales',
    latitude: 51.70347,
    longitude: -2.90332,
    spanMetres: 3200
  },
  {
    key: 'wales:crickhowell',
    name: 'Crickhowell',
    country: 'Wales',
    region: 'wales',
    latitude: 51.85992,
    longitude: -3.13771,
    spanMetres: 3200
  },
  {
    key: 'wales:brecon',
    name: 'Brecon',
    country: 'Wales',
    region: 'wales',
    latitude: 51.94612,
    longitude: -3.38887,
    spanMetres: 3200
  },
  {
    key: 'wales:hay-on-wye',
    name: 'Hay-on-Wye',
    country: 'Wales',
    region: 'wales',
    latitude: 52.07049,
    longitude: -3.12741,
    spanMetres: 3200
  },
  {
    key: 'wales:builth-wells',
    name: 'Builth Wells',
    country: 'Wales',
    region: 'wales',
    latitude: 52.1494,
    longitude: -3.40469,
    spanMetres: 3200
  },
  {
    key: 'wales:llandrindod-wells',
    name: 'Llandrindod Wells',
    country: 'Wales',
    region: 'wales',
    latitude: 52.24164,
    longitude: -3.37868,
    spanMetres: 3200
  },
  {
    key: 'wales:llanwrtyd-wells',
    name: 'Llanwrtyd Wells',
    country: 'Wales',
    region: 'wales',
    latitude: 52.10659,
    longitude: -3.63924,
    spanMetres: 3200
  },
  {
    key: 'wales:newtown',
    name: 'Newtown',
    country: 'Wales',
    region: 'wales',
    latitude: 52.51667,
    longitude: -3.3,
    spanMetres: 3200
  },
  {
    key: 'wales:welshpool',
    name: 'Welshpool',
    country: 'Wales',
    region: 'wales',
    latitude: 52.65973,
    longitude: -3.1471,
    spanMetres: 3200
  },
  {
    key: 'wales:llanidloes',
    name: 'Llanidloes',
    country: 'Wales',
    region: 'wales',
    latitude: 52.44977,
    longitude: -3.53997,
    spanMetres: 3200
  },
  {
    key: 'wales:llangollen',
    name: 'Llangollen',
    country: 'Wales',
    region: 'wales',
    latitude: 52.96829,
    longitude: -3.17127,
    spanMetres: 3200
  },
  {
    key: 'wales:ruthin',
    name: 'Ruthin',
    country: 'Wales',
    region: 'wales',
    latitude: 53.11368,
    longitude: -3.31782,
    spanMetres: 3200
  },
  {
    key: 'wales:denbigh',
    name: 'Denbigh',
    country: 'Wales',
    region: 'wales',
    latitude: 53.18333,
    longitude: -3.41667,
    spanMetres: 3200
  },
  {
    key: 'wales:rhyl',
    name: 'Rhyl',
    country: 'Wales',
    region: 'wales',
    latitude: 53.31929,
    longitude: -3.49228,
    spanMetres: 5000
  },
  {
    key: 'wales:prestatyn',
    name: 'Prestatyn',
    country: 'Wales',
    region: 'wales',
    latitude: 53.33748,
    longitude: -3.40776,
    spanMetres: 3200
  },
  {
    key: 'wales:mold',
    name: 'Mold',
    country: 'Wales',
    region: 'wales',
    latitude: 53.16674,
    longitude: -3.14143,
    spanMetres: 3200
  },
  {
    key: 'wales:holyhead',
    name: 'Holyhead',
    country: 'Wales',
    region: 'wales',
    latitude: 53.30621,
    longitude: -4.63211,
    spanMetres: 3200
  },
  {
    key: 'wales:beaumaris',
    name: 'Beaumaris',
    country: 'Wales',
    region: 'wales',
    latitude: 53.26315,
    longitude: -4.09233,
    spanMetres: 3200
  },
  {
    key: 'wales:llanfairpwllgwyngyll',
    name: 'Llanfairpwllgwyngyll',
    country: 'Wales',
    region: 'wales',
    latitude: 53.22141,
    longitude: -4.20329,
    spanMetres: 3200
  },
  {
    key: 'wales:betws-y-coed',
    name: 'Betws-y-Coed',
    country: 'Wales',
    region: 'wales',
    latitude: 53.09382,
    longitude: -3.80668,
    spanMetres: 3200
  },
  {
    key: 'wales:blaenau-ffestiniog',
    name: 'Blaenau Ffestiniog',
    country: 'Wales',
    region: 'wales',
    latitude: 52.99464,
    longitude: -3.93697,
    spanMetres: 3200
  },
  {
    key: 'wales:llanberis',
    name: 'Llanberis',
    country: 'Wales',
    region: 'wales',
    latitude: 53.11809,
    longitude: -4.12923,
    spanMetres: 3200
  },
  {
    key: 'wales:criccieth',
    name: 'Criccieth',
    country: 'Wales',
    region: 'wales',
    latitude: 52.92053,
    longitude: -4.2346,
    spanMetres: 3200
  },
  {
    key: 'wales:pwllheli',
    name: 'Pwllheli',
    country: 'Wales',
    region: 'wales',
    latitude: 52.8899,
    longitude: -4.41451,
    spanMetres: 3200
  },
  {
    key: 'wales:aberdyfi',
    name: 'Aberdyfi',
    country: 'Wales',
    region: 'wales',
    latitude: 52.544,
    longitude: -4.04606,
    spanMetres: 3200
  },
  {
    key: 'wales:tywyn',
    name: 'Tywyn',
    country: 'Wales',
    region: 'wales',
    latitude: 52.58578,
    longitude: -4.09276,
    spanMetres: 3200
  },
  {
    key: 'wales:bala',
    name: 'Bala',
    country: 'Wales',
    region: 'wales',
    latitude: 52.91111,
    longitude: -3.59722,
    spanMetres: 3200
  },
  {
    key: 'wales:corwen',
    name: 'Corwen',
    country: 'Wales',
    region: 'wales',
    latitude: 52.98005,
    longitude: -3.37736,
    spanMetres: 3200
  },
  {
    key: 'wales:barry',
    name: 'Barry',
    country: 'Wales',
    region: 'wales',
    latitude: 51.39979,
    longitude: -3.2838,
    spanMetres: 5000
  },
  {
    key: 'wales:penarth',
    name: 'Penarth',
    country: 'Wales',
    region: 'wales',
    latitude: 51.4386,
    longitude: -3.17342,
    spanMetres: 3200
  },
  {
    key: 'wales:cowbridge',
    name: 'Cowbridge',
    country: 'Wales',
    region: 'wales',
    latitude: 51.46028,
    longitude: -3.44167,
    spanMetres: 3200
  },
  {
    key: 'wales:llantwit-major',
    name: 'Llantwit Major',
    country: 'Wales',
    region: 'wales',
    latitude: 51.4107,
    longitude: -3.48632,
    spanMetres: 3200
  },
  {
    key: 'wales:mumbles',
    name: 'Mumbles',
    country: 'Wales',
    region: 'wales',
    latitude: 51.575,
    longitude: -4,
    spanMetres: 3200
  },
  {
    key: 'world:london',
    name: 'London',
    country: 'United Kingdom',
    region: 'world',
    latitude: 51.50853,
    longitude: -0.12574,
    spanMetres: 13000
  },
  {
    key: 'world:edinburgh',
    name: 'Edinburgh',
    country: 'United Kingdom',
    region: 'world',
    latitude: 55.95206,
    longitude: -3.19648,
    spanMetres: 7500
  },
  {
    key: 'world:glasgow',
    name: 'Glasgow',
    country: 'United Kingdom',
    region: 'world',
    latitude: 55.86515,
    longitude: -4.25763,
    spanMetres: 7500
  },
  {
    key: 'world:liverpool',
    name: 'Liverpool',
    country: 'United Kingdom',
    region: 'world',
    latitude: 53.41058,
    longitude: -2.97794,
    spanMetres: 7500
  },
  {
    key: 'world:manchester',
    name: 'Manchester',
    country: 'United Kingdom',
    region: 'world',
    latitude: 53.48095,
    longitude: -2.23743,
    spanMetres: 7500
  },
  {
    key: 'world:bristol',
    name: 'Bristol',
    country: 'United Kingdom',
    region: 'world',
    latitude: 51.45523,
    longitude: -2.59665,
    spanMetres: 7500
  },
  {
    key: 'world:bath',
    name: 'Bath',
    country: 'United Kingdom',
    region: 'world',
    latitude: 51.3751,
    longitude: -2.36172,
    spanMetres: 5000
  },
  {
    key: 'world:york',
    name: 'York',
    country: 'United Kingdom',
    region: 'world',
    latitude: 53.95763,
    longitude: -1.08271,
    spanMetres: 5000
  },
  {
    key: 'world:oxford',
    name: 'Oxford',
    country: 'United Kingdom',
    region: 'world',
    latitude: 51.75222,
    longitude: -1.25596,
    spanMetres: 5000
  },
  {
    key: 'world:cambridge',
    name: 'Cambridge',
    country: 'United Kingdom',
    region: 'world',
    latitude: 52.2,
    longitude: 0.11667,
    spanMetres: 5000
  },
  {
    key: 'world:brighton',
    name: 'Brighton',
    country: 'United Kingdom',
    region: 'world',
    latitude: 50.82838,
    longitude: -0.13947,
    spanMetres: 7500
  },
  {
    key: 'world:newcastle-upon-tyne',
    name: 'Newcastle upon Tyne',
    country: 'United Kingdom',
    region: 'world',
    latitude: 54.97328,
    longitude: -1.61396,
    spanMetres: 7500
  },
  {
    key: 'world:belfast',
    name: 'Belfast',
    country: 'United Kingdom',
    region: 'world',
    latitude: 54.59682,
    longitude: -5.92541,
    spanMetres: 7500
  },
  {
    key: 'world:dublin',
    name: 'Dublin',
    country: 'Ireland',
    region: 'world',
    latitude: 53.33306,
    longitude: -6.24889,
    spanMetres: 7500
  },
  {
    key: 'world:cork',
    name: 'Cork',
    country: 'Ireland',
    region: 'world',
    latitude: 51.89797,
    longitude: -8.47061,
    spanMetres: 5000
  },
  {
    key: 'world:galway',
    name: 'Galway',
    country: 'Ireland',
    region: 'world',
    latitude: 53.27245,
    longitude: -9.05095,
    spanMetres: 5000
  },
  {
    key: 'world:paris',
    name: 'Paris',
    country: 'France',
    region: 'world',
    latitude: 48.85341,
    longitude: 2.3488,
    spanMetres: 13000
  },
  {
    key: 'world:marseille',
    name: 'Marseille',
    country: 'France',
    region: 'world',
    latitude: 43.29695,
    longitude: 5.38107,
    spanMetres: 7500
  },
  {
    key: 'world:lyon',
    name: 'Lyon',
    country: 'France',
    region: 'world',
    latitude: 45.74906,
    longitude: 4.84789,
    spanMetres: 7500
  },
  {
    key: 'world:bordeaux',
    name: 'Bordeaux',
    country: 'France',
    region: 'world',
    latitude: 44.84124,
    longitude: -0.58046,
    spanMetres: 7500
  },
  {
    key: 'world:toulouse',
    name: 'Toulouse',
    country: 'France',
    region: 'world',
    latitude: 43.60426,
    longitude: 1.44367,
    spanMetres: 7500
  },
  {
    key: 'world:nantes',
    name: 'Nantes',
    country: 'France',
    region: 'world',
    latitude: 47.21725,
    longitude: -1.55336,
    spanMetres: 7500
  },
  {
    key: 'world:strasbourg',
    name: 'Strasbourg',
    country: 'France',
    region: 'world',
    latitude: 48.58392,
    longitude: 7.74553,
    spanMetres: 7500
  },
  {
    key: 'world:nice',
    name: 'Nice',
    country: 'France',
    region: 'world',
    latitude: 43.70313,
    longitude: 7.26608,
    spanMetres: 7500
  },
  {
    key: 'world:barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'world',
    latitude: 41.38879,
    longitude: 2.15899,
    spanMetres: 10000
  },
  {
    key: 'world:madrid',
    name: 'Madrid',
    country: 'Spain',
    region: 'world',
    latitude: 40.4165,
    longitude: -3.70256,
    spanMetres: 13000
  },
  {
    key: 'world:seville',
    name: 'Seville',
    country: 'Spain',
    region: 'world',
    latitude: 37.38283,
    longitude: -5.97317,
    spanMetres: 7500
  },
  {
    key: 'world:valencia',
    name: 'Valencia',
    country: 'Spain',
    region: 'world',
    latitude: 39.47391,
    longitude: -0.37966,
    spanMetres: 7500
  },
  {
    key: 'world:bilbao',
    name: 'Bilbao',
    country: 'Spain',
    region: 'world',
    latitude: 43.26271,
    longitude: -2.92528,
    spanMetres: 7500
  },
  {
    key: 'world:granada',
    name: 'Granada',
    country: 'Spain',
    region: 'world',
    latitude: 37.18817,
    longitude: -3.60667,
    spanMetres: 5000
  },
  {
    key: 'world:toledo',
    name: 'Toledo',
    country: 'Spain',
    region: 'world',
    latitude: 39.8581,
    longitude: -4.02263,
    spanMetres: 5000
  },
  {
    key: 'world:lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    region: 'world',
    latitude: 38.72509,
    longitude: -9.1498,
    spanMetres: 7500
  },
  {
    key: 'world:porto',
    name: 'Porto',
    country: 'Portugal',
    region: 'world',
    latitude: 41.1485,
    longitude: -8.61097,
    spanMetres: 7500
  },
  {
    key: 'world:rome',
    name: 'Rome',
    country: 'Italy',
    region: 'world',
    latitude: 41.89193,
    longitude: 12.51133,
    spanMetres: 10000
  },
  {
    key: 'world:florence',
    name: 'Florence',
    country: 'Italy',
    region: 'world',
    latitude: 43.77925,
    longitude: 11.24626,
    spanMetres: 7500
  },
  {
    key: 'world:venice',
    name: 'Venice',
    country: 'Italy',
    region: 'world',
    latitude: 45.43713,
    longitude: 12.33265,
    spanMetres: 5000
  },
  {
    key: 'world:milan',
    name: 'Milan',
    country: 'Italy',
    region: 'world',
    latitude: 45.46427,
    longitude: 9.18951,
    spanMetres: 10000
  },
  {
    key: 'world:naples',
    name: 'Naples',
    country: 'Italy',
    region: 'world',
    latitude: 40.85216,
    longitude: 14.26811,
    spanMetres: 7500
  },
  {
    key: 'world:turin',
    name: 'Turin',
    country: 'Italy',
    region: 'world',
    latitude: 45.07049,
    longitude: 7.68682,
    spanMetres: 7500
  },
  {
    key: 'world:genoa',
    name: 'Genoa',
    country: 'Italy',
    region: 'world',
    latitude: 44.40478,
    longitude: 8.94439,
    spanMetres: 7500
  },
  {
    key: 'world:bologna',
    name: 'Bologna',
    country: 'Italy',
    region: 'world',
    latitude: 44.49381,
    longitude: 11.33875,
    spanMetres: 7500
  },
  {
    key: 'world:palermo',
    name: 'Palermo',
    country: 'Italy',
    region: 'world',
    latitude: 38.1166,
    longitude: 13.3636,
    spanMetres: 7500
  },
  {
    key: 'world:berlin',
    name: 'Berlin',
    country: 'Germany',
    region: 'world',
    latitude: 52.52437,
    longitude: 13.41053,
    spanMetres: 13000
  },
  {
    key: 'world:munich',
    name: 'Munich',
    country: 'Germany',
    region: 'world',
    latitude: 48.13743,
    longitude: 11.57549,
    spanMetres: 10000
  },
  {
    key: 'world:hamburg',
    name: 'Hamburg',
    country: 'Germany',
    region: 'world',
    latitude: 53.55073,
    longitude: 9.99302,
    spanMetres: 10000
  },
  {
    key: 'world:cologne',
    name: 'Cologne',
    country: 'Germany',
    region: 'world',
    latitude: 50.93333,
    longitude: 6.95,
    spanMetres: 7500
  },
  {
    key: 'world:dresden',
    name: 'Dresden',
    country: 'Germany',
    region: 'world',
    latitude: 51.05089,
    longitude: 13.73832,
    spanMetres: 7500
  },
  {
    key: 'world:leipzig',
    name: 'Leipzig',
    country: 'Germany',
    region: 'world',
    latitude: 51.33962,
    longitude: 12.37129,
    spanMetres: 7500
  },
  {
    key: 'world:vienna',
    name: 'Vienna',
    country: 'Austria',
    region: 'world',
    latitude: 48.20849,
    longitude: 16.37208,
    spanMetres: 10000
  },
  {
    key: 'world:salzburg',
    name: 'Salzburg',
    country: 'Austria',
    region: 'world',
    latitude: 47.79941,
    longitude: 13.04399,
    spanMetres: 5000
  },
  {
    key: 'world:zurich',
    name: 'Zurich',
    country: 'Switzerland',
    region: 'world',
    latitude: 47.36667,
    longitude: 8.55,
    spanMetres: 7500
  },
  {
    key: 'world:geneva',
    name: 'Geneva',
    country: 'Switzerland',
    region: 'world',
    latitude: 46.20222,
    longitude: 6.14569,
    spanMetres: 7500
  },
  {
    key: 'world:bern',
    name: 'Bern',
    country: 'Switzerland',
    region: 'world',
    latitude: 46.94809,
    longitude: 7.44744,
    spanMetres: 5000
  },
  {
    key: 'world:amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    region: 'world',
    latitude: 52.37403,
    longitude: 4.88969,
    spanMetres: 7500
  },
  {
    key: 'world:rotterdam',
    name: 'Rotterdam',
    country: 'Netherlands',
    region: 'world',
    latitude: 51.9225,
    longitude: 4.47917,
    spanMetres: 7500
  },
  {
    key: 'world:utrecht',
    name: 'Utrecht',
    country: 'Netherlands',
    region: 'world',
    latitude: 52.09083,
    longitude: 5.12222,
    spanMetres: 5000
  },
  {
    key: 'world:delft',
    name: 'Delft',
    country: 'Netherlands',
    region: 'world',
    latitude: 52.00667,
    longitude: 4.35556,
    spanMetres: 5000
  },
  {
    key: 'world:brussels',
    name: 'Brussels',
    country: 'Belgium',
    region: 'world',
    latitude: 50.85045,
    longitude: 4.34878,
    spanMetres: 7500
  },
  {
    key: 'world:bruges',
    name: 'Bruges',
    country: 'Belgium',
    region: 'world',
    latitude: 51.20892,
    longitude: 3.22424,
    spanMetres: 5000
  },
  {
    key: 'world:antwerp',
    name: 'Antwerp',
    country: 'Belgium',
    region: 'world',
    latitude: 51.22047,
    longitude: 4.40026,
    spanMetres: 7500
  },
  {
    key: 'world:ghent',
    name: 'Ghent',
    country: 'Belgium',
    region: 'world',
    latitude: 51.05,
    longitude: 3.71667,
    spanMetres: 5000
  },
  {
    key: 'world:prague',
    name: 'Prague',
    country: 'Czechia',
    region: 'world',
    latitude: 50.08804,
    longitude: 14.42076,
    spanMetres: 7500
  },
  {
    key: 'world:brno',
    name: 'Brno',
    country: 'Czechia',
    region: 'world',
    latitude: 49.19522,
    longitude: 16.60796,
    spanMetres: 7500
  },
  {
    key: 'world:budapest',
    name: 'Budapest',
    country: 'Hungary',
    region: 'world',
    latitude: 47.49835,
    longitude: 19.04045,
    spanMetres: 10000
  },
  {
    key: 'world:warsaw',
    name: 'Warsaw',
    country: 'Poland',
    region: 'world',
    latitude: 52.22977,
    longitude: 21.01178,
    spanMetres: 10000
  },
  {
    key: 'world:krakow',
    name: 'Krakow',
    country: 'Poland',
    region: 'world',
    latitude: 50.06143,
    longitude: 19.93658,
    spanMetres: 7500
  },
  {
    key: 'world:gdansk',
    name: 'Gdansk',
    country: 'Poland',
    region: 'world',
    latitude: 54.35227,
    longitude: 18.64912,
    spanMetres: 7500
  },
  {
    key: 'world:copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    region: 'world',
    latitude: 55.67594,
    longitude: 12.56553,
    spanMetres: 7500
  },
  {
    key: 'world:aarhus',
    name: 'Aarhus',
    country: 'Denmark',
    region: 'world',
    latitude: 56.15674,
    longitude: 10.21076,
    spanMetres: 5000
  },
  {
    key: 'world:stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    region: 'world',
    latitude: 59.32938,
    longitude: 18.06871,
    spanMetres: 7500
  },
  {
    key: 'world:gothenburg',
    name: 'Gothenburg',
    country: 'Sweden',
    region: 'world',
    latitude: 57.70716,
    longitude: 11.96679,
    spanMetres: 7500
  },
  {
    key: 'world:oslo',
    name: 'Oslo',
    country: 'Norway',
    region: 'world',
    latitude: 59.91273,
    longitude: 10.74609,
    spanMetres: 7500
  },
  {
    key: 'world:bergen',
    name: 'Bergen',
    country: 'Norway',
    region: 'world',
    latitude: 60.39299,
    longitude: 5.32415,
    spanMetres: 5000
  },
  {
    key: 'world:tromso',
    name: 'Tromso',
    country: 'Norway',
    region: 'world',
    latitude: 69.6489,
    longitude: 18.95508,
    spanMetres: 3200
  },
  {
    key: 'world:helsinki',
    name: 'Helsinki',
    country: 'Finland',
    region: 'world',
    latitude: 60.16952,
    longitude: 24.93545,
    spanMetres: 7500
  },
  {
    key: 'world:reykjavik',
    name: 'Reykjavik',
    country: 'Iceland',
    region: 'world',
    latitude: 64.13548,
    longitude: -21.89541,
    spanMetres: 5000
  },
  {
    key: 'world:tallinn',
    name: 'Tallinn',
    country: 'Estonia',
    region: 'world',
    latitude: 59.43696,
    longitude: 24.75353,
    spanMetres: 5000
  },
  {
    key: 'world:riga',
    name: 'Riga',
    country: 'Latvia',
    region: 'world',
    latitude: 56.946,
    longitude: 24.10589,
    spanMetres: 7500
  },
  {
    key: 'world:vilnius',
    name: 'Vilnius',
    country: 'Lithuania',
    region: 'world',
    latitude: 54.68916,
    longitude: 25.2798,
    spanMetres: 7500
  },
  {
    key: 'world:athens',
    name: 'Athens',
    country: 'Greece',
    region: 'world',
    latitude: 37.98376,
    longitude: 23.72784,
    spanMetres: 10000
  },
  {
    key: 'world:thessaloniki',
    name: 'Thessaloniki',
    country: 'Greece',
    region: 'world',
    latitude: 40.64072,
    longitude: 22.93493,
    spanMetres: 7500
  },
  {
    key: 'world:istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    region: 'world',
    latitude: 41.01384,
    longitude: 28.94966,
    spanMetres: 13000
  },
  {
    key: 'world:zagreb',
    name: 'Zagreb',
    country: 'Croatia',
    region: 'world',
    latitude: 45.81444,
    longitude: 15.97798,
    spanMetres: 7500
  },
  {
    key: 'world:dubrovnik',
    name: 'Dubrovnik',
    country: 'Croatia',
    region: 'world',
    latitude: 42.64125,
    longitude: 18.10909,
    spanMetres: 3200
  },
  {
    key: 'world:split',
    name: 'Split',
    country: 'Croatia',
    region: 'world',
    latitude: 43.50891,
    longitude: 16.43915,
    spanMetres: 5000
  },
  {
    key: 'world:ljubljana',
    name: 'Ljubljana',
    country: 'Slovenia',
    region: 'world',
    latitude: 46.05108,
    longitude: 14.50513,
    spanMetres: 5000
  },
  {
    key: 'world:belgrade',
    name: 'Belgrade',
    country: 'Serbia',
    region: 'world',
    latitude: 44.80401,
    longitude: 20.46513,
    spanMetres: 7500
  },
  {
    key: 'world:bucharest',
    name: 'Bucharest',
    country: 'Romania',
    region: 'world',
    latitude: 44.43225,
    longitude: 26.10626,
    spanMetres: 10000
  },
  {
    key: 'world:sofia',
    name: 'Sofia',
    country: 'Bulgaria',
    region: 'world',
    latitude: 42.69751,
    longitude: 23.32415,
    spanMetres: 7500
  },
  {
    key: 'world:valletta',
    name: 'Valletta',
    country: 'Malta',
    region: 'world',
    latitude: 35.89968,
    longitude: 14.5148,
    spanMetres: 3200
  },
  {
    key: 'world:new-york',
    name: 'New York',
    country: 'United States',
    region: 'world',
    latitude: 40.71427,
    longitude: -74.00597,
    spanMetres: 13000
  },
  {
    key: 'world:boston',
    name: 'Boston',
    country: 'United States',
    region: 'world',
    latitude: 42.35843,
    longitude: -71.05977,
    spanMetres: 7500
  },
  {
    key: 'world:philadelphia',
    name: 'Philadelphia',
    country: 'United States',
    region: 'world',
    latitude: 39.95238,
    longitude: -75.16362,
    spanMetres: 10000
  },
  {
    key: 'world:washington',
    name: 'Washington',
    country: 'United States',
    region: 'world',
    latitude: 38.89511,
    longitude: -77.03637,
    spanMetres: 10000
  },
  {
    key: 'world:chicago',
    name: 'Chicago',
    country: 'United States',
    region: 'world',
    latitude: 41.85003,
    longitude: -87.65005,
    spanMetres: 13000
  },
  {
    key: 'world:san-francisco',
    name: 'San Francisco',
    country: 'United States',
    region: 'world',
    latitude: 37.77493,
    longitude: -122.41942,
    spanMetres: 7500
  },
  {
    key: 'world:los-angeles',
    name: 'Los Angeles',
    country: 'United States',
    region: 'world',
    latitude: 34.05223,
    longitude: -118.24368,
    spanMetres: 13000
  },
  {
    key: 'world:seattle',
    name: 'Seattle',
    country: 'United States',
    region: 'world',
    latitude: 47.60621,
    longitude: -122.33207,
    spanMetres: 7500
  },
  {
    key: 'world:portland',
    name: 'Portland',
    country: 'United States',
    region: 'world',
    latitude: 45.52345,
    longitude: -122.67621,
    spanMetres: 7500
  },
  {
    key: 'world:denver',
    name: 'Denver',
    country: 'United States',
    region: 'world',
    latitude: 39.73915,
    longitude: -104.9847,
    spanMetres: 7500
  },
  {
    key: 'world:austin',
    name: 'Austin',
    country: 'United States',
    region: 'world',
    latitude: 30.26715,
    longitude: -97.74306,
    spanMetres: 7500
  },
  {
    key: 'world:new-orleans',
    name: 'New Orleans',
    country: 'United States',
    region: 'world',
    latitude: 29.95465,
    longitude: -90.07507,
    spanMetres: 7500
  },
  {
    key: 'world:savannah',
    name: 'Savannah',
    country: 'United States',
    region: 'world',
    latitude: 32.08354,
    longitude: -81.09983,
    spanMetres: 5000
  },
  {
    key: 'world:charleston',
    name: 'Charleston',
    country: 'United States',
    region: 'world',
    latitude: 32.77632,
    longitude: -79.93275,
    spanMetres: 5000
  },
  {
    key: 'world:miami',
    name: 'Miami',
    country: 'United States',
    region: 'world',
    latitude: 25.77427,
    longitude: -80.19366,
    spanMetres: 7500
  },
  {
    key: 'world:pittsburgh',
    name: 'Pittsburgh',
    country: 'United States',
    region: 'world',
    latitude: 40.44062,
    longitude: -79.99589,
    spanMetres: 7500
  },
  {
    key: 'world:detroit',
    name: 'Detroit',
    country: 'United States',
    region: 'world',
    latitude: 42.33143,
    longitude: -83.04575,
    spanMetres: 10000
  },
  {
    key: 'world:minneapolis',
    name: 'Minneapolis',
    country: 'United States',
    region: 'world',
    latitude: 44.97997,
    longitude: -93.26384,
    spanMetres: 7500
  },
  {
    key: 'world:santa-fe',
    name: 'Santa Fe',
    country: 'United States',
    region: 'world',
    latitude: 35.68698,
    longitude: -105.9378,
    spanMetres: 5000
  },
  {
    key: 'world:salt-lake-city',
    name: 'Salt Lake City',
    country: 'United States',
    region: 'world',
    latitude: 40.76078,
    longitude: -111.89105,
    spanMetres: 7500
  },
  {
    key: 'world:honolulu',
    name: 'Honolulu',
    country: 'United States',
    region: 'world',
    latitude: 21.30694,
    longitude: -157.85833,
    spanMetres: 7500
  },
  {
    key: 'world:san-diego',
    name: 'San Diego',
    country: 'United States',
    region: 'world',
    latitude: 32.71571,
    longitude: -117.16472,
    spanMetres: 10000
  },
  {
    key: 'world:nashville',
    name: 'Nashville',
    country: 'United States',
    region: 'world',
    latitude: 36.16589,
    longitude: -86.78444,
    spanMetres: 7500
  },
  {
    key: 'world:providence',
    name: 'Providence',
    country: 'United States',
    region: 'world',
    latitude: 41.82399,
    longitude: -71.41283,
    spanMetres: 5000
  },
  {
    key: 'world:toronto',
    name: 'Toronto',
    country: 'Canada',
    region: 'world',
    latitude: 43.70643,
    longitude: -79.39864,
    spanMetres: 13000
  },
  {
    key: 'world:montreal',
    name: 'Montreal',
    country: 'Canada',
    region: 'world',
    latitude: 45.50884,
    longitude: -73.58781,
    spanMetres: 10000
  },
  {
    key: 'world:quebec-city',
    name: 'Quebec City',
    country: 'Canada',
    region: 'world',
    latitude: 46.81228,
    longitude: -71.21454,
    spanMetres: 7500
  },
  {
    key: 'world:ottawa',
    name: 'Ottawa',
    country: 'Canada',
    region: 'world',
    latitude: 45.41117,
    longitude: -75.69812,
    spanMetres: 7500
  },
  {
    key: 'world:halifax',
    name: 'Halifax',
    country: 'Canada',
    region: 'world',
    latitude: 44.64269,
    longitude: -63.57688,
    spanMetres: 5000
  },
  {
    key: 'world:st-john-s',
    name: "St. John's",
    country: 'Canada',
    region: 'world',
    latitude: 47.56494,
    longitude: -52.70931,
    spanMetres: 5000
  },
  {
    key: 'world:winnipeg',
    name: 'Winnipeg',
    country: 'Canada',
    region: 'world',
    latitude: 49.8844,
    longitude: -97.14704,
    spanMetres: 7500
  },
  {
    key: 'world:calgary',
    name: 'Calgary',
    country: 'Canada',
    region: 'world',
    latitude: 51.05011,
    longitude: -114.08529,
    spanMetres: 10000
  },
  {
    key: 'world:edmonton',
    name: 'Edmonton',
    country: 'Canada',
    region: 'world',
    latitude: 53.55014,
    longitude: -113.46871,
    spanMetres: 10000
  },
  {
    key: 'world:saskatoon',
    name: 'Saskatoon',
    country: 'Canada',
    region: 'world',
    latitude: 52.13238,
    longitude: -106.66892,
    spanMetres: 7500
  },
  {
    key: 'world:whitehorse',
    name: 'Whitehorse',
    country: 'Canada',
    region: 'world',
    latitude: 60.71611,
    longitude: -135.05375,
    spanMetres: 3200
  },
  {
    key: 'world:yellowknife',
    name: 'Yellowknife',
    country: 'Canada',
    region: 'world',
    latitude: 62.45411,
    longitude: -114.37248,
    spanMetres: 3200
  },
  {
    key: 'world:mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    region: 'world',
    latitude: 19.42847,
    longitude: -99.12766,
    spanMetres: 13000
  },
  {
    key: 'world:guadalajara',
    name: 'Guadalajara',
    country: 'Mexico',
    region: 'world',
    latitude: 20.67738,
    longitude: -103.34749,
    spanMetres: 10000
  },
  {
    key: 'world:oaxaca',
    name: 'Oaxaca',
    country: 'Mexico',
    region: 'world',
    latitude: 17.06025,
    longitude: -96.72544,
    spanMetres: 5000
  },
  {
    key: 'world:merida',
    name: 'Merida',
    country: 'Mexico',
    region: 'world',
    latitude: 20.967,
    longitude: -89.62318,
    spanMetres: 7500
  },
  {
    key: 'world:havana',
    name: 'Havana',
    country: 'Cuba',
    region: 'world',
    latitude: 23.13302,
    longitude: -82.38304,
    spanMetres: 7500
  },
  {
    key: 'world:bogota',
    name: 'Bogota',
    country: 'Colombia',
    region: 'world',
    latitude: 4.60971,
    longitude: -74.08175,
    spanMetres: 10000
  },
  {
    key: 'world:cartagena',
    name: 'Cartagena',
    country: 'Colombia',
    region: 'world',
    latitude: 10.39817,
    longitude: -75.49328,
    spanMetres: 5000
  },
  {
    key: 'world:lima',
    name: 'Lima',
    country: 'Peru',
    region: 'world',
    latitude: -12.04318,
    longitude: -77.02824,
    spanMetres: 10000
  },
  {
    key: 'world:cusco',
    name: 'Cusco',
    country: 'Peru',
    region: 'world',
    latitude: -13.53188,
    longitude: -71.96701,
    spanMetres: 5000
  },
  {
    key: 'world:quito',
    name: 'Quito',
    country: 'Ecuador',
    region: 'world',
    latitude: -0.22985,
    longitude: -78.52495,
    spanMetres: 7500
  },
  {
    key: 'world:santiago',
    name: 'Santiago',
    country: 'Chile',
    region: 'world',
    latitude: -33.45694,
    longitude: -70.64827,
    spanMetres: 10000
  },
  {
    key: 'world:valparaiso',
    name: 'Valparaiso',
    country: 'Chile',
    region: 'world',
    latitude: -33.036,
    longitude: -71.62963,
    spanMetres: 5000
  },
  {
    key: 'world:buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    region: 'world',
    latitude: -34.61315,
    longitude: -58.37723,
    spanMetres: 13000
  },
  {
    key: 'world:montevideo',
    name: 'Montevideo',
    country: 'Uruguay',
    region: 'world',
    latitude: -34.90328,
    longitude: -56.18816,
    spanMetres: 7500
  },
  {
    key: 'world:rio-de-janeiro',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'world',
    latitude: -22.90642,
    longitude: -43.18223,
    spanMetres: 10000
  },
  {
    key: 'world:sao-paulo',
    name: 'Sao Paulo',
    country: 'Brazil',
    region: 'world',
    latitude: -23.5475,
    longitude: -46.63611,
    spanMetres: 13000
  },
  {
    key: 'world:salvador',
    name: 'Salvador',
    country: 'Brazil',
    region: 'world',
    latitude: -12.97563,
    longitude: -38.49096,
    spanMetres: 7500
  },
  {
    key: 'world:brasilia',
    name: 'Brasilia',
    country: 'Brazil',
    region: 'world',
    latitude: -15.77972,
    longitude: -47.92972,
    spanMetres: 10000
  },
  {
    key: 'world:cairo',
    name: 'Cairo',
    country: 'Egypt',
    region: 'world',
    latitude: 30.06263,
    longitude: 31.24967,
    spanMetres: 13000
  },
  {
    key: 'world:alexandria',
    name: 'Alexandria',
    country: 'Egypt',
    region: 'world',
    latitude: 31.20176,
    longitude: 29.91582,
    spanMetres: 7500
  },
  {
    key: 'world:marrakesh',
    name: 'Marrakesh',
    country: 'Morocco',
    region: 'world',
    latitude: 31.63416,
    longitude: -7.99994,
    spanMetres: 7500
  },
  {
    key: 'world:fez',
    name: 'Fez',
    country: 'Morocco',
    region: 'world',
    latitude: 34.03313,
    longitude: -5.00028,
    spanMetres: 7500
  },
  {
    key: 'world:casablanca',
    name: 'Casablanca',
    country: 'Morocco',
    region: 'world',
    latitude: 33.58831,
    longitude: -7.61138,
    spanMetres: 10000
  },
  {
    key: 'world:tunis',
    name: 'Tunis',
    country: 'Tunisia',
    region: 'world',
    latitude: 36.81897,
    longitude: 10.16579,
    spanMetres: 7500
  },
  {
    key: 'world:cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    region: 'world',
    latitude: -33.92584,
    longitude: 18.42322,
    spanMetres: 7500
  },
  {
    key: 'world:johannesburg',
    name: 'Johannesburg',
    country: 'South Africa',
    region: 'world',
    latitude: -26.20227,
    longitude: 28.04363,
    spanMetres: 10000
  },
  {
    key: 'world:durban',
    name: 'Durban',
    country: 'South Africa',
    region: 'world',
    latitude: -29.8579,
    longitude: 31.0292,
    spanMetres: 7500
  },
  {
    key: 'world:nairobi',
    name: 'Nairobi',
    country: 'Kenya',
    region: 'world',
    latitude: -1.28333,
    longitude: 36.81667,
    spanMetres: 10000
  },
  {
    key: 'world:addis-ababa',
    name: 'Addis Ababa',
    country: 'Ethiopia',
    region: 'world',
    latitude: 9.02497,
    longitude: 38.74689,
    spanMetres: 10000
  },
  {
    key: 'world:lagos',
    name: 'Lagos',
    country: 'Nigeria',
    region: 'world',
    latitude: 6.45407,
    longitude: 3.39467,
    spanMetres: 13000
  },
  {
    key: 'world:accra',
    name: 'Accra',
    country: 'Ghana',
    region: 'world',
    latitude: 5.55602,
    longitude: -0.1969,
    spanMetres: 7500
  },
  {
    key: 'world:dakar',
    name: 'Dakar',
    country: 'Senegal',
    region: 'world',
    latitude: 14.6937,
    longitude: -17.44406,
    spanMetres: 7500
  },
  {
    key: 'world:zanzibar-city',
    name: 'Zanzibar City',
    country: 'Tanzania',
    region: 'world',
    latitude: -6.16394,
    longitude: 39.19793,
    spanMetres: 3200
  },
  {
    key: 'world:jerusalem',
    name: 'Jerusalem',
    country: 'Israel',
    region: 'world',
    latitude: 31.76904,
    longitude: 35.21633,
    spanMetres: 7500
  },
  {
    key: 'world:tel-aviv',
    name: 'Tel Aviv',
    country: 'Israel',
    region: 'world',
    latitude: 32.08088,
    longitude: 34.78057,
    spanMetres: 7500
  },
  {
    key: 'world:beirut',
    name: 'Beirut',
    country: 'Lebanon',
    region: 'world',
    latitude: 33.89332,
    longitude: 35.50157,
    spanMetres: 7500
  },
  {
    key: 'world:amman',
    name: 'Amman',
    country: 'Jordan',
    region: 'world',
    latitude: 31.95522,
    longitude: 35.94503,
    spanMetres: 7500
  },
  {
    key: 'world:dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    region: 'world',
    latitude: 25.07725,
    longitude: 55.30927,
    spanMetres: 10000
  },
  {
    key: 'world:doha',
    name: 'Doha',
    country: 'Qatar',
    region: 'world',
    latitude: 25.28545,
    longitude: 51.53096,
    spanMetres: 7500
  },
  {
    key: 'world:muscat',
    name: 'Muscat',
    country: 'Oman',
    region: 'world',
    latitude: 23.58413,
    longitude: 58.40778,
    spanMetres: 7500
  },
  {
    key: 'world:isfahan',
    name: 'Isfahan',
    country: 'Iran',
    region: 'world',
    latitude: 32.65246,
    longitude: 51.67462,
    spanMetres: 7500
  },
  {
    key: 'world:tehran',
    name: 'Tehran',
    country: 'Iran',
    region: 'world',
    latitude: 35.69439,
    longitude: 51.42151,
    spanMetres: 13000
  },
  {
    key: 'world:tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'world',
    latitude: 35.6895,
    longitude: 139.69171,
    spanMetres: 13000
  },
  {
    key: 'world:kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'world',
    latitude: 35.02107,
    longitude: 135.75385,
    spanMetres: 7500
  },
  {
    key: 'world:osaka',
    name: 'Osaka',
    country: 'Japan',
    region: 'world',
    latitude: 34.69379,
    longitude: 135.50107,
    spanMetres: 10000
  },
  {
    key: 'world:sapporo',
    name: 'Sapporo',
    country: 'Japan',
    region: 'world',
    latitude: 43.06667,
    longitude: 141.35,
    spanMetres: 7500
  },
  {
    key: 'world:kanazawa',
    name: 'Kanazawa',
    country: 'Japan',
    region: 'world',
    latitude: 36.6,
    longitude: 136.61667,
    spanMetres: 5000
  },
  {
    key: 'world:seoul',
    name: 'Seoul',
    country: 'South Korea',
    region: 'world',
    latitude: 37.566,
    longitude: 126.9784,
    spanMetres: 13000
  },
  {
    key: 'world:busan',
    name: 'Busan',
    country: 'South Korea',
    region: 'world',
    latitude: 35.10168,
    longitude: 129.03004,
    spanMetres: 10000
  },
  {
    key: 'world:beijing',
    name: 'Beijing',
    country: 'China',
    region: 'world',
    latitude: 39.9075,
    longitude: 116.39723,
    spanMetres: 13000
  },
  {
    key: 'world:shanghai',
    name: 'Shanghai',
    country: 'China',
    region: 'world',
    latitude: 31.22222,
    longitude: 121.45806,
    spanMetres: 13000
  },
  {
    key: 'world:hong-kong',
    name: 'Hong Kong',
    country: 'Hong Kong',
    region: 'world',
    latitude: 22.27832,
    longitude: 114.17469,
    spanMetres: 10000
  },
  {
    key: 'world:taipei',
    name: 'Taipei',
    country: 'Taiwan',
    region: 'world',
    latitude: 25.05306,
    longitude: 121.52639,
    spanMetres: 10000
  },
  {
    key: 'world:singapore',
    name: 'Singapore',
    country: 'Singapore',
    region: 'world',
    latitude: 1.28967,
    longitude: 103.85007,
    spanMetres: 10000
  },
  {
    key: 'world:bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    region: 'world',
    latitude: 13.75398,
    longitude: 100.50144,
    spanMetres: 13000
  },
  {
    key: 'world:chiang-mai',
    name: 'Chiang Mai',
    country: 'Thailand',
    region: 'world',
    latitude: 18.79038,
    longitude: 98.98468,
    spanMetres: 5000
  },
  {
    key: 'world:hanoi',
    name: 'Hanoi',
    country: 'Vietnam',
    region: 'world',
    latitude: 21.0245,
    longitude: 105.84117,
    spanMetres: 10000
  },
  {
    key: 'world:ho-chi-minh-city',
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    region: 'world',
    latitude: 10.82302,
    longitude: 106.62965,
    spanMetres: 10000
  },
  {
    key: 'world:kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    region: 'world',
    latitude: 3.1412,
    longitude: 101.68653,
    spanMetres: 10000
  },
  {
    key: 'world:george-town',
    name: 'George Town',
    country: 'Malaysia',
    region: 'world',
    latitude: 5.41123,
    longitude: 100.33543,
    spanMetres: 5000
  },
  {
    key: 'world:jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    region: 'world',
    latitude: -6.21462,
    longitude: 106.84513,
    spanMetres: 13000
  },
  {
    key: 'world:yogyakarta',
    name: 'Yogyakarta',
    country: 'Indonesia',
    region: 'world',
    latitude: -7.80139,
    longitude: 110.36472,
    spanMetres: 7500
  },
  {
    key: 'world:manila',
    name: 'Manila',
    country: 'Philippines',
    region: 'world',
    latitude: 14.6042,
    longitude: 120.9822,
    spanMetres: 13000
  },
  {
    key: 'world:delhi',
    name: 'Delhi',
    country: 'India',
    region: 'world',
    latitude: 28.65195,
    longitude: 77.23149,
    spanMetres: 13000
  },
  {
    key: 'world:mumbai',
    name: 'Mumbai',
    country: 'India',
    region: 'world',
    latitude: 19.07283,
    longitude: 72.88261,
    spanMetres: 13000
  },
  {
    key: 'world:jaipur',
    name: 'Jaipur',
    country: 'India',
    region: 'world',
    latitude: 26.91962,
    longitude: 75.78781,
    spanMetres: 10000
  },
  {
    key: 'world:kolkata',
    name: 'Kolkata',
    country: 'India',
    region: 'world',
    latitude: 22.56263,
    longitude: 88.36304,
    spanMetres: 13000
  },
  {
    key: 'world:chennai',
    name: 'Chennai',
    country: 'India',
    region: 'world',
    latitude: 13.08784,
    longitude: 80.27847,
    spanMetres: 10000
  },
  {
    key: 'world:varanasi',
    name: 'Varanasi',
    country: 'India',
    region: 'world',
    latitude: 25.31668,
    longitude: 83.01041,
    spanMetres: 7500
  },
  {
    key: 'world:kathmandu',
    name: 'Kathmandu',
    country: 'Nepal',
    region: 'world',
    latitude: 27.70169,
    longitude: 85.3206,
    spanMetres: 7500
  },
  {
    key: 'world:colombo',
    name: 'Colombo',
    country: 'Sri Lanka',
    region: 'world',
    latitude: 6.93548,
    longitude: 79.84868,
    spanMetres: 7500
  },
  {
    key: 'world:sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'world',
    latitude: -33.86785,
    longitude: 151.20732,
    spanMetres: 13000
  },
  {
    key: 'world:melbourne',
    name: 'Melbourne',
    country: 'Australia',
    region: 'world',
    latitude: -37.814,
    longitude: 144.96332,
    spanMetres: 13000
  },
  {
    key: 'world:brisbane',
    name: 'Brisbane',
    country: 'Australia',
    region: 'world',
    latitude: -27.46794,
    longitude: 153.02809,
    spanMetres: 10000
  },
  {
    key: 'world:perth',
    name: 'Perth',
    country: 'Australia',
    region: 'world',
    latitude: -31.95224,
    longitude: 115.8614,
    spanMetres: 10000
  },
  {
    key: 'world:adelaide',
    name: 'Adelaide',
    country: 'Australia',
    region: 'world',
    latitude: -34.92866,
    longitude: 138.59863,
    spanMetres: 7500
  },
  {
    key: 'world:hobart',
    name: 'Hobart',
    country: 'Australia',
    region: 'world',
    latitude: -42.87936,
    longitude: 147.32941,
    spanMetres: 5000
  },
  {
    key: 'world:auckland',
    name: 'Auckland',
    country: 'New Zealand',
    region: 'world',
    latitude: -36.84853,
    longitude: 174.76349,
    spanMetres: 10000
  },
  {
    key: 'world:wellington',
    name: 'Wellington',
    country: 'New Zealand',
    region: 'world',
    latitude: -41.28664,
    longitude: 174.77557,
    spanMetres: 7500
  },
  {
    key: 'world:christchurch',
    name: 'Christchurch',
    country: 'New Zealand',
    region: 'world',
    latitude: -43.53333,
    longitude: 172.63333,
    spanMetres: 7500
  },
  {
    key: 'world:dunedin',
    name: 'Dunedin',
    country: 'New Zealand',
    region: 'world',
    latitude: -45.87416,
    longitude: 170.50361,
    spanMetres: 5000
  },
  {
    key: 'world:ulaanbaatar',
    name: 'Ulaanbaatar',
    country: 'Mongolia',
    region: 'world',
    latitude: 47.90771,
    longitude: 106.88324,
    spanMetres: 7500
  },
  {
    key: 'world:almaty',
    name: 'Almaty',
    country: 'Kazakhstan',
    region: 'world',
    latitude: 43.25249,
    longitude: 76.9115,
    spanMetres: 10000
  },
  {
    key: 'world:tashkent',
    name: 'Tashkent',
    country: 'Uzbekistan',
    region: 'world',
    latitude: 41.26465,
    longitude: 69.21627,
    spanMetres: 10000
  },
  {
    key: 'world:samarkand',
    name: 'Samarkand',
    country: 'Uzbekistan',
    region: 'world',
    latitude: 39.65456,
    longitude: 66.96445,
    spanMetres: 7500
  }
]
